version: '3.8'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: splitmate-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: splitmate
      POSTGRES_USER: splitmate_user
      POSTGRES_PASSWORD: splitmate_password
      POSTGRES_ROOT_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/src/database/postgres-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U splitmate_user -d splitmate"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    networks:
      - splitmate-network-postgres

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: splitmate-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@splitmate.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - splitmate-network-postgres

  # Backend API (Supabase JWT Development)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.postgres.dev
    container_name: splitmate-backend-jwt-dev
    restart: unless-stopped
    env_file:
      - backend/.env.postgres
    environment:
      # PostgreSQL Database Connection (override defaults)
      DATABASE_URL: postgresql://splitmate_user:splitmate_password@postgres:5432/splitmate
      DB_HOST: postgres
      DB_USER: splitmate_user
      DB_PASSWORD: splitmate_password
      DB_NAME: splitmate
      DB_PORT: 5432
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - splitmate-network-postgres

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: splitmate-frontend-postgres-dev
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: http://localhost:3001
      VITE_FRONTEND_URL: http://localhost:5173
      # Google OAuth Client ID (set when testing)
      # VITE_GOOGLE_CLIENT_ID: your-google-client-id
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - splitmate-network-postgres

volumes:
  postgres_data_dev:

networks:
  splitmate-network-postgres:
    driver: bridge 
